/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t elektra_boiler_cap.gltf
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
  }
  materials: {
    ['Phenolic (Amber)']: THREE.MeshStandardMaterial
  }
}

export function ElektraBoilerCap(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./gltfs/elektra_boiler_cap.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-1.75, 0, 0]} scale={.5}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Phenolic (Amber)']} rotation={[Math.PI / 9, 0, 0]} scale={1} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[0,0,0]} />
    </group>
  )
} 

useGLTF.preload('./gltfs/elektra_boiler_cap.gltf')
