/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t elektra_steam_knob.gltf
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
  }
  materials: {
    ['Phenolic (Amber)']: THREE.MeshStandardMaterial
  }
}

export function ElektraSteamKnob(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./gltfs/elektra_steam_knob.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-1.09, 0, 2]} scale={0.1}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Phenolic (Amber)']} position={[0,0,0]} scale={10} />
      </group>
      <pointLight intensity={1} decay={2} color="#fcfcfc" position={[-12.44, 12.49, 15.73]} />
    </group>
  )
}

useGLTF.preload('./gltfs/elektra_steam_knob.gltf')
